#!/bin/sh

usage () {	echo "How to launch a shiny app for a specific sample.
		Example: sh shiny.sh -p /home/luisns/Desktop/test/results -s 022 
		
		-h,	prints this help
		-p,	path to the files (absolute prefered although relative also accepted)
		-s,	sample name (the part before .depthquality.csv)
		* -p, -s are mandatory parameters

		
		OUTPUT: 
			This program launches a shiny app.
			It uses the file *.depthquality.csv, previosly generated by the QY program (main.sh)
			and allows the user to check, per sample and position, depth, quality and relative percentage of mismatches.
			It also shows the percentage of the genome that would be covered depending on the user's selection for
			those 3 parameters.

		CHECK:
			QY (main.sh) needs to have been launched in advance in order to generate the necessary file (*.depthquality.csv).
			Therefore, R, Rstudio and the libraries ggplot2 and shiny should already be installed in your system.
			The file *.depthquality.csv doesn't need to be in the 'results' folder created by QY (main.sh)
			or in a folder named 'results'. Nevertheless, in the same folder where it is placed,
			the file referencelength needs to be present."
		exit 1 ; }


#the arguments and options introduced by the user are checked to confirm that the instructions have been followed
#in case there is an error, an error message is shown as well as the usage norms
#the arguments for the different options are saved in variables that are used in the subsequent analysis of the files
if [ $1 = "-h" ] 2>/dev/null;then
	usage
else
	if [ $# -ne 4 ]; then
		echo "Error: The command to execute the program is not correct. Wrong number of fields.\n"
		usage
	else
		if ! [ $1 = "-p" -a $3 = "-s" ]; then 
			echo "Error: Invalid options used.\n"
			usage
		else
			if ! [ -d "$2" ]; then
				echo "Error: The path to the files is incorrect."
				exit 1
			else 
				if ! [ -f "$2/$4.depthquality.csv" ]; then
					echo "Error: The necessary file does not exist."
					echo "Check the name of the sample as well as the presence of its *.depthquality.csv file in the directory given".
					exit 1
				else
					while getopts :p:s: options; do
					  case ${options} in
					    p )
					      path=$OPTARG
				              ;;
					    s )
					      name=$OPTARG
					      ;;			 
					  esac
					done
				fi
			fi
		fi
	fi
fi

#the presence of the other necessary file is checked
if ! [ -f "$2/referencelength" ]; then
	echo "Error: The referencelength file does not exist."
	exit 1
fi

#although previously checked in the main.sh script, again
#it is checked that R and Rstudio are installed
if ! [ -x "$(command -v R)" ]; then
 	echo 'Error: R is not installed.'
 	exit 1
fi

if ! [ -x "$(command -v rstudio)" ]; then
 	echo 'Error: Rstudio is not installed.'
 	exit 1
fi

#as well as the libraries needed
Rscript check.R 2>null
error=$(grep -c "Error" null)
if [ $error -gt 0 ];then
	echo "Error: Check that the libraries needed in R are installed (knitr, ggplot2, egg, plotly and shiny)."
	rm null
	exit 1
fi
rm null

echo "Launching the shiny app...\n"					
Rscript -e 'library(methods); shiny::runApp("app.R", launch.browser = TRUE)' $path $name 2>/dev/null
#once the webpage is closed, the command finishes too
echo "Thanks for using the QY program.\n"

